### ISSUE TITLE
[BUG] Node 17 - Issue with hashing

### ISSUE THREAD

**Issue by gabriel-glo** [infinum/eightshift-frontend-libs#495]
When build is ran with Node 17 we get the following error:

```bash
> npm start

> @eightshift/boilerplate@6.0.0 start
> webpack --progress --watch --mode development

10% building 0/4 modules 4 active ...let/boilerplate/wp-content/themes/boilerplate/src/Blocks/assets/application-blocks-editor.jsnode:internal/crypto/hash:67
  this[kHandle] = new _Hash(algorithm, xofLen);
                  ^

Error: error:0308010C:digital envelope routines::unsupported
    at new Hash (node:internal/crypto/hash:67:19)
    at Object.createHash (node:crypto:130:10)
    at module.exports (/Users/gg/valet/boilerplate/wp-content/themes/boilerplate/node_modules/webpack/lib/util/createHash.js:135:53)
    at NormalModule._initBuildHash (/Users/gg/valet/boilerplate/wp-content/themes/boilerplate/node_modules/webpack/lib/NormalModule.js:417:16)
    at handleParseError (/Users/gg/valet/boilerplate/wp-content/themes/boilerplate/node_modules/webpack/lib/NormalModule.js:471:10)
    at /Users/gg/valet/boilerplate/wp-content/themes/boilerplate/node_modules/webpack/lib/NormalModule.js:503:5
    at /Users/gg/valet/boilerplate/wp-content/themes/boilerplate/node_modules/webpack/lib/NormalModule.js:358:12
    at /Users/gg/valet/boilerplate/wp-content/themes/boilerplate/node_modules/loader-runner/lib/LoaderRunner.js:373:3
    at iterateNormalLoaders (/Users/gg/valet/boilerplate/wp-content/themes/boilerplate/node_modules/loader-runner/lib/LoaderRunner.js:214:10)
    at iterateNormalLoaders (/Users/gg/valet/boilerplate/wp-content/themes/boilerplate/node_modules/loader-runner/lib/LoaderRunner.js:221:10) {
  opensslErrorStack: [ 'error:03000086:digital envelope routines::initialization error' ],
  library: 'digital envelope routines',
  reason: 'unsupported',
  code: 'ERR_OSSL_EVP_UNSUPPORTED'
}

Node.js v17.1.0

```

It seems that there was a change in hashing algorithm. Excerpt from: https://nodejs.org/en/blog/release/v17.0.0/

>  If you hit an ERR_OSSL_EVP_UNSUPPORTED error in your application with Node.js 17, it’s likely that your application or a module you’re using is attempting to use an algorithm or key size which is no longer allowed by default with OpenSSL 3.0. A command-line option, --openssl-legacy-provider, has been added to revert to the legacy provider as a temporary workaround for these tightened restrictions.

**Comment by moonbyt3** [comment]
I've researched a little bit. 
Solution should be to add export NODE_OPTIONS to `npm start` command in package.json, ie:

```
{
  ...
  "scripts": {
    ...
    "start": "export NODE_OPTIONS=--openssl-legacy-provider; webpack --progress --watch --mode development",
    ...
  },
 ...
}
```

I'm curious if we should support experimental versions of Node. Current LTS version is 16.13.1, however if you update Node to 17.1.0 you can run `npm start` without this hash error. One of solutions could be adding if-node-version package, but I think it would add unnecessary complexity. So is it worth adding these features for minor version of Node? Shouldn't we use LTS version?

**Comment by moonbyt3** [comment]
Also, running scripts when providing value to scripts.start is ordinary shell so something like this should be possible
`if [ x`(node -v)` = x'v17.0.0' ]; then echo 'should make comparison it work with regex maybe and then run different script'; else npm run start; fi`
:sunglasses:

**Comment by moonbyt3** [comment]
One of the solutions I've found is pasting this in webpack.config
`const crypto = require("crypto");
const crypto_orig_createHash = crypto.createHash;
crypto.createHash = algorithm => crypto_orig_createHash(algorithm == "md4" ? "sha256" : algorithm);`

I still have to check this on my local if it's working, then I'll edit this comment.

**Comment by iruzevic** [comment]
this is fixed
